name: Deploy to Vercel

on:
  push:
    branches:
      - main # Adjust this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cleanup unnecessary files
        run: |
          find . -name "*.pyc" -exec rm -f {} \;
          find . -name "__pycache__" -exec rm -rf {} \;
          find . -name "*.log" -exec rm -f {} \;
          rm -rf tests/
          rm -rf docs/
          # Add other directories/files that are not needed

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./

      - name: Cleanup
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /tmp/*
